config/routes.rb
Tasker::Application.routes.draw do
  get "confi_load/Load"
  resources :config_files
  resources :tasks

  get "welcome/index"

  root 'welcome#index'

end

app/models/config_file.rb
class ConfigFile < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/confi_load_controller.rb
class ConfiLoadController < ApplicationController
    def Load
        require 'find'
        $searchpath = 'D:\files'
        $pattern = '*'

        Find.find($searchpath) do |path|
            if FileTest.directory?(path)
            else
                lines = File.readlines(path)
                line_count = lines.size
                text = lines.join
                @config_file = ConfigFile.new
                @config_file.object_type = File.basename(path).split('.')[0].to_s
                @config_file.config     = 'test'
                @config_file.name       = File.basename(path)
                @config_file.full_name  = File.path(path)
                @config_file.text       = text
                @config_file.save
                File.delete(path)
            end
        end
    end
end

app/controllers/config_files_controller.rb
class ConfigFilesController < ApplicationController
  before_action :set_config_file, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json, :js
  # GET /config_files
  # GET /config_files.json
  def index

    #@config_files = ConfigFile.all
    @config_files = ConfigFile.paginate(:page => params[:page], :per_page => 30)
    #respond_with @config_files

  end

  # GET /config_files/1
  # GET /config_files/1.json
  def show
  end

  # GET /config_files/new
  def new
    @config_file = ConfigFile.new
  end

  # GET /config_files/1/edit
  def edit
  end

  # POST /config_files
  # POST /config_files.json
  def create
    @config_file = ConfigFile.new(config_file_params)

    respond_to do |format|
      if @config_file.save
        format.html { redirect_to @config_file, notice: 'Config file was successfully created.' }
        format.json { render action: 'show', status: :created, location: @config_file }
      else
        format.html { render action: 'new' }
        format.json { render json: @config_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /config_files/1
  # PATCH/PUT /config_files/1.json
  def update
    respond_to do |format|
      if @config_file.update(config_file_params)
        format.html { redirect_to @config_file, notice: 'Config file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @config_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /config_files/1
  # DELETE /config_files/1.json
  def destroy
    @config_file.destroy
    respond_to do |format|
      format.html { redirect_to config_files_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config_file
      @config_file = ConfigFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_file_params
      params.require(:config_file).permit(:config, :name, :full_name,:object_type,:date, :text)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:subject, :description, :StartDate, :EndDate, :complete)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confi_load_helper.rb
module ConfiLoadHelper
end

app/helpers/config_files_helper.rb
module ConfigFilesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/confi_load/Load.html.erb
<h1>ConfiLoad#Load</h1>
<p>Find me in app/views/confi_load/Load.html.erb</p>

app/views/config_files/_form.html.erb
<%= form_for(@config_file) do |f| %>
  <% if @config_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@config_file.errors.count, "error") %> prohibited this config_file from being saved:</h2>

      <ul>
      <% @config_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :config %><br>
    <%= f.text_field :config %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

<pre code>
  <div class="field">

    <%= f.text_area :text %>
  </div>
  </pre>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/config_files/edit.html.erb
<h1>Editing config_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @config_file %> |
<%= link_to 'Back', config_files_path %>

app/views/config_files/index.html.erb
<h3 xmlns="http://www.w3.org/1999/html">список объектов</h3>
<%= will_paginate @config_files, renderer: BootstrapPagination::Rails %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>конфигурация</th>
      <th>имя</th>
      <th>тип объекта</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @config_files.each do |config_file| %>
      <tr>
        <td><%= config_file.config %></td>
        <td><%= config_file.name %></td>
        <td><%= config_file.object_type %></td>
        <td>
          <div class="btn-group btn-group-xs">
            <%= link_to 'S', config_file , class: 'btn btn-default'%>
            <%= link_to 'E', edit_config_file_path(config_file), class: 'btn btn-default' %>
            <%= link_to 'D', config_file, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-default'%>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tr>
    <td colspan="4">
      <%= will_paginate @config_files, renderer: BootstrapPagination::Rails %>
    </td>
  </tr>
</table>

<br>

app/views/config_files/new.html.erb
<h1>New config_file</h1>

<%= render 'form' %>

<%= link_to 'Back', config_files_path %>

app/views/config_files/show.html.erb
<p id="notice"><%= notice %></p>
<!--<div class="alert alert-success">...</div>-->



<div class="row">
  <div class="col-sm-10">
    <div class="panel panel-default">
      <div class="panel-heading" data-toggle="collapse" data-target="#file_text_panel">
        <div id="file_text"><h5><%= @config_file.name %> <span class="caret"></span></h5></div>
      </div>
      <div id="file_text_panel" class="collapse">
        <div class="panel-body"><pre><code><%=@config_file.text%></code></pre></div>
      </div>
    </div>

    <!-- комментарии - старт -->
    <div class="panel panel-default">
      <div class="panel-heading" data-toggle="collapse" data-target="#comments_panel">
        <div id="comments"><h5>комментарии<span class="caret"></span></h5></div>
      </div>
      <div id="comments_panel" class="collapse">
        <div class="panel-body">

          <form>
            <input name="title" type="text" placeholder="Title?" />
            <textarea name="content" data-provide="markdown" rows="10"></textarea>

            <hr/>
            <button type="submit" class="btn">Submit</button>
          </form>

        </div>
      </div>
    </div>
    <!-- -->



  </div>
  <div class="col-sm-2">
    <div data-spy="affix" data-offset-top="60" data-offset-bottom="200">


      <ul class="list-group">
        <li class="list-group-item">
        <%= link_to 'Edit', edit_config_file_path(@config_file) %> |
        <%= link_to 'Back', config_files_path %>
        </li>
        <li class="list-group-item">
          <span class="badge"><%= @config_file.config %></span>
          Конфигурация
        </li>
        <li class="list-group-item">
          <span class="badge"><%= @config_file.object_type %></span>
          Тип объекта
        </li>
        <i class="fa fa-camera-retro"></i> fa-camera-retro
      </ul>


    </div>
  </div>
</div>


<script type="text/javascript">
    $("#content").markdown({language:'ru'})
    $('#file_text_panel').on('hidden.bs.collapse', function () {
      // $('#file_text').text('<span class="caret"></span>')
    })
    $('#file_text_panel').on('show.bs.collapse', function () {
       // $('#file_text').text('(нажмите чтобы скрыть текст файла)')
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
  $(document).ready(function() {
      hljs.initHighlightingOnLoad();
   });
  </script>
</head>
<body>


<div class="container">
      <!-- Static navbar -->

      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">###</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li>
                <form class="navbar-form navbar-left" role="search">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="поиск...">
                  </div>

                </form>

              </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">



              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">1</a></li>
                  <li><a href="#">2</a></li>
                  <li><a href="#">3</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">4</li>
                  <li><a href="#">4.1</a></li>
                  <li><a href="#">4.2</a></li>
                </ul>
              </li>



              <!--<li class="active"><a href="./">Меню</a></li>-->
              <!--<li><a href="#">11</a></li>-->
              <!--<li><a href="#">DD</a></li>-->
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

</div>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="container-fluid">

          <%= yield %>

      </div>


   <!--    <span class="label label-default">обычное</span>
<span class="label label-primary">основной</span>
<span class="label label-success">выполнено</span>
<span class="label label-info">информация</span>
<span class="label label-warning">предупреждение</span>
<span class="label label-danger">критично</span> -->



</body>

</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :StartDate %><br>
    <%= f.date_select :StartDate %>
  </div>
  <div class="field">
    <%= f.label :EndDate %><br>
    <%= f.date_select :EndDate %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Description</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Complete</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.subject %></td>
        <td><%= task.description %></td>
        <td><%= task.StartDate %></td>
        <td><%= task.EndDate %></td>
        <td><%= task.complete %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="alert alert-success"><%= notice %></div>

<p>
  <strong>Subject:</strong>
  <%= @task.subject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @task.StartDate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @task.EndDate %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>